### ISSUE TITLE
Divephase DA?

### ISSUE THREAD

**Issue by SimonDedman** [spluque/diveMove#3]
Hi Sebastian, thanks for diveMove and the paper, it looks like it has excellent potential.
I'm trying to use it to analyse dive behaviour of tuna, which don't go to the surface exactly but often come shallow. I'm having a few problems which I'll file separately for neatness.

Please can you let me know what DA means for getDPhaseLab(dcalib)? The other 6 are explained in the paper:

descent = D
descent/bottom = DB
bottom = B
bottom/ascent = BA
ascent = A
DA??
X = surface

It would be great if these were listed in the details section of the function, for ease of access.

Thanks!

**Comment by biadias** [comment]
DA refers to Descent/ascent, which means that no bottom was detected but there is a change on directionality. 

Bellow is the text extracted direct from the package documentation available on CRAN:

"Once dives have been detected and assigned to a period of wet activity, phases within dives are
identified using the descent, ascent and wiggle criteria (see ‘Detection of dive phases’ below). This
procedure generates a factor with levels “D”, “DB”, “B”, “BA”, “DA”, “A”, and “X”, breaking the input into descent, descent/bottom, bottom, bottom/ascent, ascent, descent/ascent (ocurring when
no bottom phase can be detected) and non-dive (surface), respectively."

**Comment by SimonDedman** [comment]
Thanks!
