### ISSUE TITLE
dive.activity meanings

### ISSUE THREAD

**Issue by SimonDedman** [spluque/diveMove#4]
Hi again,

Please could you let me know a little more what getDAct(dcalib)$dive.activity levels mean? FOr my result (with number of rows per category) I have:

L dry, 0
W wet, 587
U underwater (above dive depth), 21093
D diving, 21520
Z trivial wet animal activities, 0

U and D I understand, above and below dive.thr? So what is wet? And what does Z mean?

Thanks!

**Comment by biadias** [comment]
As I understand W means number of wet phases (which on your results looks like all phases). Z is the number of short wet activities, in this case if you were dealing with an animal that spend part of it's time in the dry phase it would be the equivalent of really short periods underwater (however, it is not your case).

**Comment by SimonDedman** [comment]
Interesting, thanks for the reply. So shouldn't W equal all U+D phases then?

**Comment by biadias** [comment]
Yes indeed it should be. Keep in mind that these values are generated from calibrate functions. They are depended on the thresholds you set up in your calibrateDepth() function to generate your TDRcalibrate. 
The CRAN documentation has a good explanation about how W L U D are generated.

**Comment by SimonDedman** [comment]
Ok good stuff, thanks again. I think my original attempts failed and this is why my numbers are off. Seb just popped up on here offering to help so hopefully we'll make some progress.

Oh hey, I've just seen you're at MBARI! I'm just down the road at Hopkins :)

**Comment by spluque** [comment]
> Interesting, thanks for the reply. So shouldn't W equal all U+D phases then?

Not necessarily.  `W` is a segment of data that may be surrounded by "dry" segments.  See the "Details" section of the help for `calibrateDepth`, particularly the second paragraph, and consider how whatever tag you're using is recording time stamps and depth and/or any processing you've done prior to calling `calibrateDepth`.

**Comment by SimonDedman** [comment]
Thanks for the intel, much appreciated
