### ISSUE TITLE
calibrateDepth detect n dives; diveStats report n-1 dives

### ISSUE THREAD

**Issue by ChrisOosthuizen** [spluque/diveMove#8]
# calibrateDepth detect n dives; diveStats report n-1 dives

**calibrateDepth** reports the number of dives in the data. **diveStats** reports the statistics for all the dives. Often, the same number of dives are identified in calibrateDepth and diveStats.
However, with some data sets, calibrateDepth detect n dives and diveStats report n-1 dives. "Losing" one dive has consequences for my downstream analysis, so I am trying to understand this behavior. (Note: it always seems to be n-1, rather than another number).

Below I provide analysis code and two data files (one with 52 dives detected in calibrateDepth and diveStats; one with 60 dives detected in calibrateDepth and 59 reported in diveStats.

I am using diveMove_1.6.1 and R version 4.3.2 (2023-10-31 ucrt). Platform: x86_64-w64-mingw32/x64 (64-bit)

Thanks for a great package! 

```R

library(diveMove)

# read in one of the csv:
dat <- read.csv("./test_input2.csv")       # calibrateDepth =! diveStats
#dat <- read.csv("./test_input_fine2.csv")  # calibrateDepth = diveStats

dat$date.time = as.POSIXct(dat$date.time, format="%Y/%m/%d %H:%M:%S")

# now start creating the TDR dive object
filename = "Divedata"
  
# Choose a depth threshold (in m) and time threshold (in sec) to define a dive
# The time threshold is used to filter dives after DiveMove calculated dives.
depth.threshold = 3
  
tdr <- createTDR(time = dat$date.time, 
                   depth = dat$depth, 
                   speed = FALSE, 
                   dtime = 1,   #  sampling interval used in seconds
                   file = filename)
  
show(tdr)
  
# start detecting individual dives
tdr.calib <- calibrateDepth(tdr,
                              dive.thr = depth.threshold, # only select dives deeper than threshold
                              zoc.method='filter',
                              k=c(3, 5760),
                              probs=c(0.5, 0.02),
                              dry.thr=3600, 
                              wet.thr=60*5, 
                              interp.wet=FALSE, 
                              smooth.par=0.1,
                              knot.factor=20, 
                              descent.crit.q=0.01, ascent.crit.q=0.01,
                              na.rm=T)
  
tdr.dat = as.data.frame(tdr.calib@tdr)
head(tdr.dat)
  
# create dive summary metrics for each dive 
dive.stats <- diveStats(tdr.calib)        
head(dive.stats)
  
nrow(dive.stats)

```
[test_input_fine2.csv](https://github.com/spluque/diveMove/files/13940544/test_input_fine2.csv)
[test_input2.csv](https://github.com/spluque/diveMove/files/13940545/test_input2.csv)

**Comment by spluque** [comment]
@ChrisOosthuizen This occurs because the last dive (60th) in your example has incomplete data, hence it's impossible to calculate meaningful statistics for that one. You could have detected that if you had plotted the TDR object as the first step after reading the data file. In fact, examining results at every stage exposes many issues and helps make adjustments.
